name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Tags
        run: git fetch --prune --tags

      - name: Configure CI Git User
        run: |
          git config --global user.name 'JPBBot'
          git config --global user.email 'jpbbot@users.noreply.github.com'
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@jpbbot"

      - name: Install Dependencies
        run: npm install --also=dev

      - name: Publish Library
        run: NODE_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}} npx lerna publish --yes